apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-ingress-2
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: simpleapp.local.host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app-service
            port:
              number: 80
  - host: simpleapp2.local.host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app-service-2
            port:
              number: 80