apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-provider-02
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "9346f7e9-0fe7-4129-a783-54c23119128a" 
    keyvaultName: "devops-kv-03"      
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: secret2
          objectType: secret              
          objectVersion: ""               
    tenantId: "b3dc8175-7891-4b01-9e44-8e18fa4277f0"                