apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-provider-env
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "4d72b591-1434-4731-ade6-28bc35bd8341" #ClientID
    keyvaultName: "devops-kv-03"      
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: secret2
          objectType: secret              
          objectVersion: ""            
    tenantId: "b3dc8175-7891-4b01-9e44-8e18fa4277f0"                