{{- if (eq .Values.deployment "deployment") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demoapp.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "demoapp.fullname" . }}-{{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        {{- include "demoapp.labels" . | nindent 4 }}
    spec:
      nodeSelector:
        managedBy: {{ .Values.deployment.nodeSelector.managedBy }}
        environment: {{ .Values.deployment.nodeSelector.environment }}
      containers:
        - name: {{ include "demoapp.fullname" . }}
          image: "{{ .Values.deployment.container.image.repo }}:{{.Values.deployment.container.image.tag}}"
          ports:
            - containerPort: {{ .Values.deployment.container.port.containerPort }}
              name: {{ .Values.deployment.container.port.name }}
          resources:
            {{- toYaml .Values.resources | nindent 6 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 6 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}