apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.scprovider.name }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: {{ .Values.scprovider.kubeletident }} #ClientID
    keyvaultName: {{ .Values.scprovider.devopsvault }}      
    cloudName: ""
    {{ - with .Values.scprovider.object }}
      objects:
        array:
        {{ - toYaml . | nindent 8}}
    {{- end -}}                                  
    tenantId: {{ .Values.scprovider.tenantId }}         