apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-02
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-02-deploy
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # scale up if usage is above
        # 99% of the requested CPU (100m)
        averageUtilization: 99
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 99
  #Custom metrics
  #- type: Pods
  #  pods:
  #    metric:
  #      name: requests_per_second
  #    target:
  #      type: AverageValue
  #      averageValue: "50"