apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-provider-env-02
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "9b944839-bce4-499b-a302-ccbafe751528" #ClientID
    keyvaultName: "devops-vault-03"      
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: secret2
          objectType: secret              
          objectVersion: ""
        - |
          objectName: secret1
          objectType: secret              
          objectVersion: ""            
    tenantId: "b3dc8175-7891-4b01-9e44-8e18fa4277f0"                