apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-provider-env
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "315f113e-a24f-48a5-8524-b0bfe6ae31f2" #ClientID
    keyvaultName: "devops-vault-03"      
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: secret2
          objectType: secret              
          objectVersion: ""            
    tenantId: "b3dc8175-7891-4b01-9e44-8e18fa4277f0"                